volumes:
  plugin-src:

services:
  traefik:
    build: .
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.web.transport.lifeCycle.graceTimeOut=0"
      - "--log.level=DEBUG"
      - "--experimental.localPlugins.rewritebody.modulename=github.com/motoki317/traefik-rewritebody-wasm"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    develop:
      watch:
        - action: rebuild
          path: .

  whoami:
    image: traefik/whoami
    command:
      - -verbose
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.routers.whoami.middlewares=rewritebody"
      - "traefik.http.middlewares.rewritebody.plugin.rewritebody.rewrites[0].from=whoami"
      - "traefik.http.middlewares.rewritebody.plugin.rewritebody.rewrites[0].to=REWRITTEN"
